# Generated by Django 3.1 on 2020-08-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_hi', models.BooleanField(default=True)),
                ('hi_text', models.CharField(blank=True, max_length=50, null=True)),
                ('ask_lo', models.BooleanField(default=True)),
                ('lo_text', models.CharField(blank=True, max_length=50, null=True)),
                ('ask_emotion', models.BooleanField(default=True)),
                ('emotion_text', models.CharField(blank=True, max_length=50, null=True)),
                ('ask_name', models.BooleanField(default=True)),
                ('name_text', models.CharField(blank=True, max_length=50, null=True)),
                ('ask_place', models.BooleanField(default=True)),
                ('place_text', models.CharField(blank=True, max_length=50, null=True)),
                ('ask_question', models.BooleanField(default=False)),
                ('question_text', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.location')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi', models.CharField(blank=True, max_length=200, null=True)),
                ('lo', models.CharField(blank=True, max_length=200, null=True)),
                ('emotion', models.CharField(blank=True, choices=[('happy', 'Happy'), ('meh', 'Meh'), ('sad', 'Sad')], default='meh', max_length=8, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.poll')),
            ],
        ),
    ]
