# Generated by Django 3.0.8 on 2020-08-25 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askHi', models.BooleanField(default=True)),
                ('HiText', models.CharField(blank=True, max_length=50, null=True)),
                ('askLo', models.BooleanField(default=True)),
                ('LoText', models.CharField(blank=True, max_length=50, null=True)),
                ('askEmotion', models.BooleanField(default=True)),
                ('EmotionText', models.CharField(blank=True, max_length=50, null=True)),
                ('askName', models.BooleanField(default=True)),
                ('NameText', models.CharField(blank=True, max_length=50, null=True)),
                ('askPlace', models.BooleanField(default=True)),
                ('PlaceText', models.CharField(blank=True, max_length=50, null=True)),
                ('askQuestion', models.BooleanField(default=True)),
                ('QuestionText', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi', models.CharField(blank=True, max_length=200, null=True)),
                ('lo', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Poll')),
            ],
        ),
    ]
