# Generated by Django 3.0.8 on 2020-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='emotion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
