# Generated by Django 3.1 on 2020-08-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='emotion_text',
            field=models.CharField(blank=True, default='how are you feeling today?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='hi_text',
            field=models.CharField(blank=True, default='What was the <span class="hi">Hi</span> of this we', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='lo_text',
            field=models.CharField(blank=True, default='What was the <span class="lo">Lo</span> of this we', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name_text',
            field=models.CharField(blank=True, default="what's your name?", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='place_text',
            field=models.CharField(blank=True, default='where are you from?', max_length=50, null=True),
        ),
    ]
