# Generated by Django 3.1 on 2020-08-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200826_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.location'),
        ),
    ]
