# Generated by Django 3.0.8 on 2020-08-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_answer_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='emotion',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('meh', 'Meh'), ('sad', 'Sad')], default='meh', max_length=8, null=True),
        ),
    ]
