# Generated by Django 3.1 on 2020-08-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200826_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hero',
            field=models.ImageField(default='hero.png', upload_to='heros'),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
