# Generated by Django 3.1 on 2020-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200826_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hero',
            field=models.ImageField(default='hero.png', upload_to='heros/<django.db.models.fields.CharField>-hero.png'),
        ),
    ]
