# Generated by Django 3.1 on 2020-08-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200826_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
