# Generated by Django 3.1 on 2020-09-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20200827_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ask_emotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='ask_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='place_text',
            field=models.CharField(blank=True, default='fill it out by writing #HiLo and finishing it with where you’re from (Ex. #HiLoArlington, #HiLoDC)', max_length=100, null=True),
        ),
    ]
